(function (global) {
  function img(text, bg, fg) {
    bg = bg || '#EBF4FF';
    fg = fg || '#1F2937';
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="400"><rect width="100%" height="100%" fill="${bg}"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" font-family="Inter, Arial" font-size="42" fill="${fg}">${text}</text></svg>`;
    return 'data:image/svg+xml;utf8,' + encodeURIComponent(svg);
  }

  const categories = [
    { name: 'Electronics', slug: 'electronics' },
    { name: 'Home Appliances', slug: 'home-appliances' },
    { name: 'Fashion', slug: 'fashion' },
    { name: 'Shoes', slug: 'shoes' },
    { name: 'Beauty', slug: 'beauty' },
    { name: 'Sports', slug: 'sports' },
    { name: 'Groceries', slug: 'groceries' },
    { name: 'Televisions', slug: 'televisions' },
    { name: 'Tablets', slug: 'tablets' },
    { name: 'Audio', slug: 'audio' },
    { name: 'Smart Home', slug: 'smart-home' },
    { name: 'Kitchen', slug: 'kitchen' },
    { name: 'Furniture', slug: 'furniture' },
    { name: 'Toys', slug: 'toys' },
    { name: 'Books', slug: 'books' },
    { name: 'Automotive', slug: 'automotive' },
    { name: 'Garden & Outdoor', slug: 'garden-outdoor' },
  ];


  const baseProducts = [
    // Smartphones & Tablets (Electronics)
    {
      id: 1,
      title: 'Samsung Galaxy S24 5G',
      description: '6.2" Dynamic AMOLED 2X, 8GB RAM, 256GB storage, 5G, triple camera.',
      price: 74999,
      discountPercentage: 10,
      rating: 4.7,
      stock: 40,
      brand: 'Samsung',
      category: 'electronics',
      thumbnail: img('Galaxy S24', '#DBEAFE'),
      images: [img('Galaxy S24', '#DBEAFE'), img('Galaxy S24 Back', '#BFDBFE')]
    },
    {
      id: 2,
      title: 'Apple iPhone 15',
      description: '6.1" Super Retina XDR, A16 Bionic, 128GB storage, dual camera.',
      price: 79999,
      discountPercentage: 6,
      rating: 4.8,
      stock: 30,
      brand: 'Apple',
      category: 'electronics',
      thumbnail: img('iPhone 15', '#DBEAFE'),
      images: [img('iPhone 15', '#DBEAFE')]
    },
    {
      id: 3,
      title: 'OnePlus 12R 5G',
      description: 'Snapdragon 8 series, 8GB RAM, 256GB, 5500mAh battery, 100W fast charging.',
      price: 39999,
      discountPercentage: 12,
      rating: 4.6,
      stock: 55,
      brand: 'OnePlus',
      category: 'electronics',
      thumbnail: img('OnePlus 12R', '#DBEAFE'),
      images: [img('OnePlus 12R', '#DBEAFE')]
    },
    {
      id: 4,
      title: 'Xiaomi Redmi Note 13 Pro',
      description: '6.67" AMOLED, 200MP camera, 8GB RAM, 256GB storage.',
      price: 28999,
      discountPercentage: 15,
      rating: 4.5,
      stock: 70,
      brand: 'Xiaomi',
      category: 'electronics',
      thumbnail: img('Redmi Note 13 Pro', '#DBEAFE'),
      images: [img('Redmi Note 13 Pro', '#DBEAFE')]
    },
    {
      id: 5,
      title: 'Apple iPad 10th Gen Wi‑Fi 64GB',
      description: '10.9" Liquid Retina, A14 Bionic, ideal for study and entertainment.',
      price: 34999,
      discountPercentage: 8,
      rating: 4.7,
      stock: 35,
      brand: 'Apple',
      category: 'tablets',
      thumbnail: img('iPad 10th Gen', '#E9D5FF'),
      images: [img('iPad 10th Gen', '#E9D5FF')]
    },
    {
      id: 6,
      title: 'Samsung Galaxy Tab S9 FE',
      description: '10.9" display, S Pen in box, 6GB RAM, 128GB storage, Dolby Atmos.',
      price: 34999,
      discountPercentage: 10,
      rating: 4.5,
      stock: 28,
      brand: 'Samsung',
      category: 'tablets',
      thumbnail: img('Galaxy Tab S9 FE', '#E9D5FF'),
      images: [img('Galaxy Tab S9 FE', '#E9D5FF')]
    },

    // Laptops (Electronics)
    {
      id: 7,
      title: 'HP Pavilion 14 AMD Ryzen 5',
      description: '14" FHD, Ryzen 5, 16GB RAM, 512GB SSD, Windows 11, backlit keyboard.',
      price: 62999,
      discountPercentage: 18,
      rating: 4.4,
      stock: 25,
      brand: 'HP',
      category: 'electronics',
      thumbnail: img('HP Pavilion 14', '#DBEAFE'),
      images: [img('HP Pavilion 14', '#DBEAFE')]
    },
    {
      id: 8,
      title: 'ASUS TUF Gaming F15',
      description: '15.6" 144Hz, Intel i5, RTX 4050, 16GB RAM, 512GB SSD.',
      price: 89999,
      discountPercentage: 15,
      rating: 4.5,
      stock: 18,
      brand: 'ASUS',
      category: 'electronics',
      thumbnail: img('ASUS TUF F15', '#DBEAFE'),
      images: [img('ASUS TUF F15', '#DBEAFE')]
    },

    // Televisions
    {
      id: 9,
      title: 'Sony Bravia 55" 4K UHD Smart TV',
      description: '4K HDR, Google TV, Dolby Vision, Dolby Atmos, bezel-less design.',
      price: 71999,
      discountPercentage: 13,
      rating: 4.6,
      stock: 22,
      brand: 'Sony',
      category: 'televisions',
      thumbnail: img('Sony Bravia 55 4K', '#C7D2FE'),
      images: [img('Sony Bravia 55 4K', '#C7D2FE')]
    },
    {
      id: 10,
      title: 'LG 43" 4K Smart LED TV',
      description: 'Ultra HD, WebOS, built-in OTT apps, AI sound.',
      price: 34999,
      discountPercentage: 17,
      rating: 4.5,
      stock: 35,
      brand: 'LG',
      category: 'televisions',
      thumbnail: img('LG 43 4K TV', '#C7D2FE'),
      images: [img('LG 43 4K TV', '#C7D2FE')]
    },

    // Audio & Wearables
    {
      id: 11,
      title: 'boAt Airdopes 141 TWS Earbuds',
      description: 'Up to 42 hours playback, ENx noise cancellation, IPX4.',
      price: 1499,
      discountPercentage: 25,
      rating: 4.3,
      stock: 150,
      brand: 'boAt',
      category: 'audio',
      thumbnail: img('boAt Airdopes 141', '#FDE68A'),
      images: [img('boAt Airdopes 141', '#FDE68A')]
    },
    {
      id: 12,
      title: 'Sony WH-CH720N Wireless Headphones',
      description: 'Active noise cancellation, 35h battery, lightweight over-ear design.',
      price: 9990,
      discountPercentage: 20,
      rating: 4.6,
      stock: 60,
      brand: 'Sony',
      category: 'audio',
      thumbnail: img('Sony WH-CH720N', '#FDE68A'),
      images: [img('Sony WH-CH720N', '#FDE68A')]
    },
    {
      id: 13,
      title: 'Noise ColorFit Pro 4 Max Smartwatch',
      description: '1.8" AMOLED display, Bluetooth calling, SpO2 & heart-rate tracking.',
      price: 3999,
      discountPercentage: 28,
      rating: 4.2,
      stock: 110,
      brand: 'Noise',
      category: 'electronics',
      thumbnail: img('Noise ColorFit Pro 4', '#DBEAFE'),
      images: [img('Noise ColorFit Pro 4', '#DBEAFE')]
    },

    // Home Appliances
    {
      id: 14,
      title: 'LG 1.5 Ton 5 Star Inverter Split AC',
      description: 'Dual inverter compressor, 4-way swing, energy efficient cooling.',
      price: 45999,
      discountPercentage: 18,
      rating: 4.4,
      stock: 20,
      brand: 'LG',
      category: 'home-appliances',
      thumbnail: img('LG 1.5 Ton AC', '#DCFCE7'),
      images: [img('LG 1.5 Ton AC', '#DCFCE7')]
    },
    {
      id: 15,
      title: 'Philips Air Fryer 4.1L',
      description: 'Rapid air technology, low oil frying, digital touch panel.',
      price: 10499,
      discountPercentage: 22,
      rating: 4.5,
      stock: 45,
      brand: 'Philips',
      category: 'kitchen',
      thumbnail: img('Philips Air Fryer', '#FFE4E6'),
      images: [img('Philips Air Fryer', '#FFE4E6')]
    },
    {
      id: 16,
      title: 'Prestige Electric Kettle 1.5L',
      description: 'Stainless steel body, auto cut-off, 1500W.',
      price: 1899,
      discountPercentage: 30,
      rating: 4.3,
      stock: 100,
      brand: 'Prestige',
      category: 'kitchen',
      thumbnail: img('Prestige Kettle', '#FFE4E6'),
      images: [img('Prestige Kettle', '#FFE4E6')]
    },

    // Groceries (FMCG)
    {
      id: 17,
      title: 'Tata Salt 1kg',
      description: 'Iodised vacuum evaporated salt, trusted Indian brand.',
      price: 28,
      discountPercentage: 5,
      rating: 4.7,
      stock: 500,
      brand: 'Tata',
      category: 'groceries',
      thumbnail: img('Tata Salt 1kg', '#E0E7FF'),
      images: [img('Tata Salt 1kg', '#E0E7FF')]
    },
    {
      id: 18,
      title: 'Aashirvaad Atta 10kg',
      description: 'Whole wheat flour, chakki ground, soft rotis.',
      price: 529,
      discountPercentage: 10,
      rating: 4.6,
      stock: 220,
      brand: 'Aashirvaad',
      category: 'groceries',
      thumbnail: img('Aashirvaad Atta 10kg', '#E0E7FF'),
      images: [img('Aashirvaad Atta 10kg', '#E0E7FF')]
    },
    {
      id: 19,
      title: 'Amul Taaza Toned Milk 1L (Tetra Pak)',
      description: 'Toned milk, long-life UHT processed, no need to boil.',
      price: 74,
      discountPercentage: 3,
      rating: 4.5,
      stock: 300,
      brand: 'Amul',
      category: 'groceries',
      thumbnail: img('Amul Taaza 1L', '#E0E7FF'),
      images: [img('Amul Taaza 1L', '#E0E7FF')]
    },
    {
      id: 20,
      title: 'Maggi 2-Minute Noodles Masala 12 Pack',
      description: 'Classic masala flavour, family pack of instant noodles.',
      price: 210,
      discountPercentage: 12,
      rating: 4.4,
      stock: 260,
      brand: 'Nestlé Maggi',
      category: 'groceries',
      thumbnail: img('Maggi Masala Pack', '#E0E7FF'),
      images: [img('Maggi Masala Pack', '#E0E7FF')]
    },

    // Beauty & Personal Care
    {
      id: 21,
      title: 'Lakmé 9 to 5 Primer + Matte Foundation',
      description: 'Long-wear matte liquid foundation with built-in primer.',
      price: 499,
      discountPercentage: 22,
      rating: 4.2,
      stock: 140,
      brand: 'Lakmé',
      category: 'beauty',
      thumbnail: img('Lakme 9 to 5 Foundation', '#FFE4E6'),
      images: [img('Lakme 9 to 5 Foundation', '#FFE4E6')]
    },
    {
      id: 22,
      title: 'Dove Intense Repair Shampoo 650ml',
      description: 'Nourishing shampoo for damaged hair with fibre actives.',
      price: 449,
      discountPercentage: 18,
      rating: 4.4,
      stock: 160,
      brand: 'Dove (HUL)',
      category: 'beauty',
      thumbnail: img('Dove Intense Repair', '#FFE4E6'),
      images: [img('Dove Intense Repair', '#FFE4E6')]
    },
    {
      id: 23,
      title: 'Mamaearth Vitamin C Face Wash 250ml',
      description: 'Paraben-free face wash with vitamin C and turmeric.',
      price: 349,
      discountPercentage: 20,
      rating: 4.3,
      stock: 130,
      brand: 'Mamaearth',
      category: 'beauty',
      thumbnail: img('Mamaearth Vit C Face Wash', '#FFE4E6'),
      images: [img('Mamaearth Vit C Face Wash', '#FFE4E6')]
    },

    // Fashion & Footwear
    {
      id: 24,
      title: 'Adidas Runfalcon 3.0 Running Shoes (Men)',
      description: 'Breathable mesh upper, cushioned midsole, ideal for daily runs.',
      price: 5499,
      discountPercentage: 25,
      rating: 4.5,
      stock: 80,
      brand: 'Adidas',
      category: 'fashion',
      thumbnail: img('Adidas Runfalcon 3.0', '#FCE7F3'),
      images: [img('Adidas Runfalcon 3.0', '#FCE7F3')]
    },
    {
      id: 25,
      title: 'Nike Revolution 6 Running Shoes (Women)',
      description: 'Lightweight running shoes with foam cushioning and secure fit.',
      price: 5795,
      discountPercentage: 22,
      rating: 4.6,
      stock: 65,
      brand: 'Nike',
      category: 'fashion',
      thumbnail: img('Nike Revolution 6', '#FCE7F3'),
      images: [img('Nike Revolution 6', '#FCE7F3')]
    },
    {
      id: 26,
      title: 'Allen Solly Men\'s Slim Fit Formal Shirt',
      description: 'Cotton-rich, solid colour, office-ready formal shirt.',
      price: 1999,
      discountPercentage: 35,
      rating: 4.2,
      stock: 120,
      brand: 'Allen Solly',
      category: 'fashion',
      thumbnail: img('Allen Solly Formal Shirt', '#FCE7F3'),
      images: [img('Allen Solly Formal Shirt', '#FCE7F3')]
    },

    // Sports & Fitness
    {
      id: 27,
      title: 'Nivia Storm Football Size 5',
      description: 'Durable rubber football suitable for turf and grass.',
      price: 799,
      discountPercentage: 20,
      rating: 4.3,
      stock: 90,
      brand: 'Nivia',
      category: 'sports',
      thumbnail: img('Nivia Storm Football', '#FEF9C3'),
      images: [img('Nivia Storm Football', '#FEF9C3')]
    },
    {
      id: 28,
      title: 'HRX by Hrithik Roshan Yoga Mat 6mm',
      description: 'Anti-skid yoga mat with carrying strap, ideal for home workouts.',
      price: 1299,
      discountPercentage: 30,
      rating: 4.4,
      stock: 75,
      brand: 'HRX',
      category: 'sports',
      thumbnail: img('HRX Yoga Mat', '#FEF9C3'),
      images: [img('HRX Yoga Mat', '#FEF9C3')]
    },

    // Furniture & Home Decor
    {
      id: 29,
      title: 'Wakefit Orthopedic Memory Foam Mattress (Queen)',
      description: '78x60x8 inch queen mattress with orthopedic support.',
      price: 14999,
      discountPercentage: 24,
      rating: 4.6,
      stock: 30,
      brand: 'Wakefit',
      category: 'furniture',
      thumbnail: img('Wakefit Queen Mattress', '#E5E7EB'),
      images: [img('Wakefit Queen Mattress', '#E5E7EB')]
    },
    {
      id: 30,
      title: 'DeckCraft Sheesham Wood Coffee Table',
      description: 'Solid sheesham wood centre table with storage shelf.',
      price: 8999,
      discountPercentage: 20,
      rating: 4.3,
      stock: 25,
      brand: 'DeckCraft',
      category: 'furniture',
      thumbnail: img('Sheesham Coffee Table', '#E5E7EB'),
      images: [img('Sheesham Coffee Table', '#E5E7EB')]
    },

    // Books
    {
      id: 31,
      title: 'Atomic Habits by James Clear',
      description: 'Bestselling self-help book on building good habits and breaking bad ones.',
      price: 599,
      discountPercentage: 28,
      rating: 4.8,
      stock: 200,
      brand: 'Penguin Random House',
      category: 'books',
      thumbnail: img('Atomic Habits', '#FEF3C7'),
      images: [img('Atomic Habits', '#FEF3C7')]
    },
    {
      id: 32,
      title: 'The Psychology of Money by Morgan Housel',
      description: 'Timeless lessons on wealth, greed and happiness.',
      price: 499,
      discountPercentage: 25,
      rating: 4.7,
      stock: 180,
      brand: 'Jaico Publishing',
      category: 'books',
      thumbnail: img('Psychology of Money', '#FEF3C7'),
      images: [img('Psychology of Money', '#FEF3C7')]
    },

    // Automotive & Accessories
    {
      id: 33,
      title: 'Michelin Digital Tyre Inflator',
      description: 'Portable tyre inflator with digital gauge and auto cut-off.',
      price: 3499,
      discountPercentage: 18,
      rating: 4.4,
      stock: 60,
      brand: 'Michelin',
      category: 'automotive',
      thumbnail: img('Michelin Tyre Inflator', '#FDE2E2'),
      images: [img('Michelin Tyre Inflator', '#FDE2E2')]
    },
    {
      id: 34,
      title: '3M Premium Car Care Kit',
      description: 'Complete cleaning kit with shampoo, wax, dashboard dresser and cloth.',
      price: 1899,
      discountPercentage: 20,
      rating: 4.3,
      stock: 85,
      brand: '3M',
      category: 'automotive',
      thumbnail: img('3M Car Care Kit', '#FDE2E2'),
      images: [img('3M Car Care Kit', '#FDE2E2')]
    },

    // Garden & Outdoor
    {
      id: 35,
      title: 'Ikea FEJKA Artificial Potted Plant',
      description: 'Lifelike artificial plant for indoor decoration, low maintenance.',
      price: 799,
      discountPercentage: 15,
      rating: 4.2,
      stock: 90,
      brand: 'Ikea',
      category: 'garden-outdoor',
      thumbnail: img('Ikea FEJKA Plant', '#DCFCE7'),
      images: [img('Ikea FEJKA Plant', '#DCFCE7')]
    },
    {
      id: 36,
      title: 'GreenBloom 4-Tier Metal Plant Stand',
      description: 'Powder-coated metal plant stand suitable for balcony and garden.',
      price: 2499,
      discountPercentage: 22,
      rating: 4.3,
      stock: 40,
      brand: 'GreenBloom',
      category: 'garden-outdoor',
      thumbnail: img('Metal Plant Stand', '#DCFCE7'),
      images: [img('Metal Plant Stand', '#DCFCE7')]
    },

    // Smart Home (Mix of real + realistic brand)
    {
      id: 37,
      title: 'Wipro 9W Smart LED Bulb (Wi‑Fi)',
      description: 'Color-changing smart bulb with app and voice control.',
      price: 699,
      discountPercentage: 30,
      rating: 4.2,
      stock: 160,
      brand: 'Wipro',
      category: 'smart-home',
      thumbnail: img('Wipro Smart Bulb', '#D1FAE5'),
      images: [img('Wipro Smart Bulb', '#D1FAE5')]
    },
    {
      id: 38,
      title: 'NestGuard Wi‑Fi Smart Security Camera',
      description: '1080p night vision camera with two-way audio and mobile alerts.',
      price: 3999,
      discountPercentage: 21,
      rating: 4.3,
      stock: 55,
      brand: 'NestGuard',
      category: 'smart-home',
      thumbnail: img('NestGuard Security Cam', '#D1FAE5'),
      images: [img('NestGuard Security Cam', '#D1FAE5')]
    },

    // Additional Electronics (to reach at least 25 products)
    {
      id: 39,
      title: 'Google Pixel 8 5G',
      description: '6.2" Actua display, Google Tensor G3, 8GB RAM, 128GB storage, dual camera.',
      price: 75999,
      discountPercentage: 10,
      rating: 4.6,
      stock: 35,
      brand: 'Google',
      category: 'electronics',
      thumbnail: img('Google Pixel 8', '#DBEAFE'),
      images: [img('Google Pixel 8', '#DBEAFE')]
    },
    {
      id: 40,
      title: 'Samsung Galaxy S23 FE 5G',
      description: '6.4" Dynamic AMOLED 2X, Exynos 2200, 8GB RAM, 256GB storage, triple camera.',
      price: 54999,
      discountPercentage: 15,
      rating: 4.4,
      stock: 50,
      brand: 'Samsung',
      category: 'electronics',
      thumbnail: img('Galaxy S23 FE', '#DBEAFE'),
      images: [img('Galaxy S23 FE', '#DBEAFE')]
    },
    {
      id: 41,
      title: 'Motorola Edge 40 5G',
      description: '6.55" pOLED 144Hz display, Dimensity 8020, 8GB RAM, 256GB storage.',
      price: 29999,
      discountPercentage: 18,
      rating: 4.3,
      stock: 60,
      brand: 'Motorola',
      category: 'electronics',
      thumbnail: img('Motorola Edge 40', '#DBEAFE'),
      images: [img('Motorola Edge 40', '#DBEAFE')]
    },
    {
      id: 42,
      title: 'iQOO Neo 7 Pro 5G',
      description: '6.78" AMOLED 120Hz, Snapdragon 8+ Gen 1, 12GB RAM, 256GB storage, 120W charging.',
      price: 35999,
      discountPercentage: 20,
      rating: 4.5,
      stock: 55,
      brand: 'iQOO',
      category: 'electronics',
      thumbnail: img('iQOO Neo 7 Pro', '#DBEAFE'),
      images: [img('iQOO Neo 7 Pro', '#DBEAFE')]
    },
    {
      id: 43,
      title: 'vivo V29 5G',
      description: '6.78" curved AMOLED, 50MP OIS camera, 8GB RAM, 256GB storage.',
      price: 32999,
      discountPercentage: 16,
      rating: 4.2,
      stock: 48,
      brand: 'vivo',
      category: 'electronics',
      thumbnail: img('vivo V29', '#DBEAFE'),
      images: [img('vivo V29', '#DBEAFE')]
    },
    {
      id: 44,
      title: 'realme Narzo 70 Pro 5G',
      description: '6.72" AMOLED, 50MP Sony sensor, 8GB RAM, 256GB storage, 67W fast charging.',
      price: 21999,
      discountPercentage: 22,
      rating: 4.1,
      stock: 80,
      brand: 'realme',
      category: 'electronics',
      thumbnail: img('realme Narzo 70 Pro', '#DBEAFE'),
      images: [img('realme Narzo 70 Pro', '#DBEAFE')]
    },
    {
      id: 45,
      title: 'POCO X6 Pro 5G',
      description: '6.67" 1.5K AMOLED, Dimensity 8300 Ultra, 12GB RAM, 256GB storage.',
      price: 26999,
      discountPercentage: 18,
      rating: 4.4,
      stock: 65,
      brand: 'POCO',
      category: 'electronics',
      thumbnail: img('POCO X6 Pro', '#DBEAFE'),
      images: [img('POCO X6 Pro', '#DBEAFE')]
    },
    {
      id: 46,
      title: 'Nothing Phone (2)',
      description: '6.7" OLED 120Hz, Snapdragon 8+ Gen 1, 12GB RAM, 256GB storage, Glyph interface.',
      price: 49999,
      discountPercentage: 12,
      rating: 4.5,
      stock: 40,
      brand: 'Nothing',
      category: 'electronics',
      thumbnail: img('Nothing Phone 2', '#DBEAFE'),
      images: [img('Nothing Phone 2', '#DBEAFE')]
    },
    {
      id: 47,
      title: 'Apple MacBook Air 13" M2',
      description: '13.6" Liquid Retina, Apple M2 chip, 8GB RAM, 256GB SSD, macOS.',
      price: 114900,
      discountPercentage: 8,
      rating: 4.8,
      stock: 25,
      brand: 'Apple',
      category: 'electronics',
      thumbnail: img('MacBook Air M2', '#DBEAFE'),
      images: [img('MacBook Air M2', '#DBEAFE')]
    },
    {
      id: 48,
      title: 'Dell XPS 13 9315',
      description: '13.4" FHD+ display, Intel i7 12th Gen, 16GB RAM, 512GB SSD, Windows 11.',
      price: 139990,
      discountPercentage: 10,
      rating: 4.6,
      stock: 18,
      brand: 'Dell',
      category: 'electronics',
      thumbnail: img('Dell XPS 13', '#DBEAFE'),
      images: [img('Dell XPS 13', '#DBEAFE')]
    },
    {
      id: 49,
      title: 'Lenovo Legion 5 Pro',
      description: '16" QHD 165Hz, Ryzen 7, RTX 4060, 16GB RAM, 1TB SSD, gaming laptop.',
      price: 149990,
      discountPercentage: 14,
      rating: 4.7,
      stock: 20,
      brand: 'Lenovo',
      category: 'electronics',
      thumbnail: img('Lenovo Legion 5 Pro', '#DBEAFE'),
      images: [img('Lenovo Legion 5 Pro', '#DBEAFE')]
    },
    {
      id: 50,
      title: 'Acer Nitro 5 12th Gen',
      description: '15.6" FHD 144Hz, Intel i5 12th Gen, RTX 3050, 16GB RAM, 512GB SSD.',
      price: 84999,
      discountPercentage: 20,
      rating: 4.4,
      stock: 30,
      brand: 'Acer',
      category: 'electronics',
      thumbnail: img('Acer Nitro 5', '#DBEAFE'),
      images: [img('Acer Nitro 5', '#DBEAFE')]
    },
    {
      id: 51,
      title: 'MSI Modern 14',
      description: '14" FHD, Intel i5 11th Gen, 8GB RAM, 512GB SSD, lightweight ultrabook.',
      price: 59999,
      discountPercentage: 22,
      rating: 4.2,
      stock: 40,
      brand: 'MSI',
      category: 'electronics',
      thumbnail: img('MSI Modern 14', '#DBEAFE'),
      images: [img('MSI Modern 14', '#DBEAFE')]
    },
    {
      id: 52,
      title: 'Canon EOS R10 Mirrorless Camera',
      description: '24.2MP APS-C sensor, 4K60 video, dual pixel AF, RF-S 18-45mm kit lens.',
      price: 82999,
      discountPercentage: 10,
      rating: 4.6,
      stock: 22,
      brand: 'Canon',
      category: 'electronics',
      thumbnail: img('Canon EOS R10', '#DBEAFE'),
      images: [img('Canon EOS R10', '#DBEAFE')]
    },
    {
      id: 53,
      title: 'Sony Alpha a7 IV Full-Frame Camera',
      description: '33MP full-frame sensor, 4K60 recording, advanced autofocus, body only.',
      price: 214990,
      discountPercentage: 7,
      rating: 4.8,
      stock: 10,
      brand: 'Sony',
      category: 'electronics',
      thumbnail: img('Sony Alpha a7 IV', '#DBEAFE'),
      images: [img('Sony Alpha a7 IV', '#DBEAFE')]
    },
    {
      id: 54,
      title: 'GoPro HERO12 Black',
      description: '5.3K60 video, HyperSmooth stabilisation, waterproof action camera.',
      price: 45990,
      discountPercentage: 12,
      rating: 4.5,
      stock: 35,
      brand: 'GoPro',
      category: 'electronics',
      thumbnail: img('GoPro HERO12 Black', '#DBEAFE'),
      images: [img('GoPro HERO12 Black', '#DBEAFE')]
    },
    {
      id: 55,
      title: 'Samsung Galaxy Watch6 Bluetooth 44mm',
      description: 'Super AMOLED display, sleep tracking, body composition analysis, GPS.',
      price: 32999,
      discountPercentage: 18,
      rating: 4.4,
      stock: 45,
      brand: 'Samsung',
      category: 'electronics',
      thumbnail: img('Galaxy Watch6', '#DBEAFE'),
      images: [img('Galaxy Watch6', '#DBEAFE')]
    },
    {
      id: 56,
      title: 'Apple Watch SE (2nd Gen) GPS 44mm',
      description: 'Retina display, crash detection, heart-rate tracking, swimproof design.',
      price: 32900,
      discountPercentage: 10,
      rating: 4.6,
      stock: 38,
      brand: 'Apple',
      category: 'electronics',
      thumbnail: img('Apple Watch SE 2', '#DBEAFE'),
      images: [img('Apple Watch SE 2', '#DBEAFE')]
    },

    // Additional Home Appliances (to reach at least 25 products)
    {
      id: 57,
      title: 'Whirlpool 7.5 kg Fully Automatic Top Load Washing Machine',
      description: '7.5 kg 5 Star fully automatic top load with 12 wash programs and Hard Water Wash.',
      price: 23990,
      discountPercentage: 18,
      rating: 4.3,
      stock: 60,
      brand: 'Whirlpool',
      category: 'home-appliances',
      thumbnail: img('Whirlpool 7.5kg Top Load', '#DCFCE7'),
      images: [img('Whirlpool 7.5kg Top Load', '#DCFCE7')]
    },
    {
      id: 58,
      title: 'Samsung 6 kg Front Load Washing Machine EcoBubble',
      description: '6 kg 5 Star front load with EcoBubble, Hygiene Steam, and Digital Inverter.',
      price: 28990,
      discountPercentage: 15,
      rating: 4.5,
      stock: 55,
      brand: 'Samsung',
      category: 'home-appliances',
      thumbnail: img('Samsung 6kg Front Load', '#DCFCE7'),
      images: [img('Samsung 6kg Front Load', '#DCFCE7')]
    },
    {
      id: 59,
      title: 'LG 260L 3 Star Frost Free Double Door Refrigerator',
      description: 'Smart Inverter compressor, multi-air flow cooling, toughened glass shelves.',
      price: 27990,
      discountPercentage: 17,
      rating: 4.4,
      stock: 40,
      brand: 'LG',
      category: 'home-appliances',
      thumbnail: img('LG 260L Double Door', '#DCFCE7'),
      images: [img('LG 260L Double Door', '#DCFCE7')]
    },
    {
      id: 60,
      title: 'Whirlpool 200L 5 Star Single Door Refrigerator',
      description: 'Inverter compressor, insulated capillary technology, jumbo storage.',
      price: 17490,
      discountPercentage: 20,
      rating: 4.3,
      stock: 70,
      brand: 'Whirlpool',
      category: 'home-appliances',
      thumbnail: img('Whirlpool 200L Single Door', '#DCFCE7'),
      images: [img('Whirlpool 200L Single Door', '#DCFCE7')]
    },
    {
      id: 61,
      title: 'Bosch 13 Place Settings Dishwasher',
      description: 'Intensive Kadhai program for Indian utensils, EcoSilence Drive motor.',
      price: 46990,
      discountPercentage: 12,
      rating: 4.6,
      stock: 25,
      brand: 'Bosch',
      category: 'home-appliances',
      thumbnail: img('Bosch 13 Place Dishwasher', '#DCFCE7'),
      images: [img('Bosch 13 Place Dishwasher', '#DCFCE7')]
    },
    {
      id: 62,
      title: 'IFB 20L Convection Microwave Oven 20BC4',
      description: 'Convection microwave with grill, defrost, and 24 auto-cook menus.',
      price: 9990,
      discountPercentage: 22,
      rating: 4.2,
      stock: 80,
      brand: 'IFB',
      category: 'home-appliances',
      thumbnail: img('IFB 20L Convection', '#DCFCE7'),
      images: [img('IFB 20L Convection', '#DCFCE7')]
    },
    {
      id: 63,
      title: 'Panasonic 23L Convection Microwave Oven',
      description: '23L convection with Magic Grill, 61 auto menus, and compact design.',
      price: 12990,
      discountPercentage: 18,
      rating: 4.3,
      stock: 65,
      brand: 'Panasonic',
      category: 'home-appliances',
      thumbnail: img('Panasonic 23L Convection', '#DCFCE7'),
      images: [img('Panasonic 23L Convection', '#DCFCE7')]
    },
    {
      id: 64,
      title: 'Voltas 1.5 Ton 3 Star Window AC',
      description: 'High ambient cooling, copper condenser, turbo mode, anti-dust filter.',
      price: 28990,
      discountPercentage: 19,
      rating: 4.1,
      stock: 45,
      brand: 'Voltas',
      category: 'home-appliances',
      thumbnail: img('Voltas 1.5T Window AC', '#DCFCE7'),
      images: [img('Voltas 1.5T Window AC', '#DCFCE7')]
    },
    {
      id: 65,
      title: 'Blue Star 1 Ton 5 Star Inverter Split AC',
      description: 'Inverter compressor, anti-bacterial filter, eco mode, copper condenser.',
      price: 36990,
      discountPercentage: 16,
      rating: 4.4,
      stock: 38,
      brand: 'Blue Star',
      category: 'home-appliances',
      thumbnail: img('Blue Star 1T Inverter AC', '#DCFCE7'),
      images: [img('Blue Star 1T Inverter AC', '#DCFCE7')]
    },
    {
      id: 66,
      title: 'Kent Grand RO+UV+UF Water Purifier 8L',
      description: 'Multiple purification by RO+UV+UF, mineral RO technology, wall mountable.',
      price: 15990,
      discountPercentage: 20,
      rating: 4.3,
      stock: 90,
      brand: 'Kent',
      category: 'home-appliances',
      thumbnail: img('Kent Grand 8L', '#DCFCE7'),
      images: [img('Kent Grand 8L', '#DCFCE7')]
    },
    {
      id: 67,
      title: 'Aquaguard Aura RO+UV+UF+MTDS 7L',
      description: 'RO+UV+UF+MTDS purification with Active Copper Zinc Booster technology.',
      price: 14990,
      discountPercentage: 18,
      rating: 4.2,
      stock: 85,
      brand: 'Eureka Forbes',
      category: 'home-appliances',
      thumbnail: img('Aquaguard Aura 7L', '#DCFCE7'),
      images: [img('Aquaguard Aura 7L', '#DCFCE7')]
    },
    {
      id: 68,
      title: 'Philips Air Purifier AC1215/20',
      description: 'HEPA filter, removes 99.97% pollutants, ideal for bedroom up to 333 sq ft.',
      price: 10990,
      discountPercentage: 21,
      rating: 4.4,
      stock: 75,
      brand: 'Philips',
      category: 'home-appliances',
      thumbnail: img('Philips AC1215/20', '#DCFCE7'),
      images: [img('Philips AC1215/20', '#DCFCE7')]
    },
    {
      id: 69,
      title: 'Dyson V8 Absolute Cord-Free Vacuum Cleaner',
      description: 'Powerful suction, up to 40 minutes fade-free power, whole machine filtration.',
      price: 34990,
      discountPercentage: 10,
      rating: 4.6,
      stock: 25,
      brand: 'Dyson',
      category: 'home-appliances',
      thumbnail: img('Dyson V8 Absolute', '#DCFCE7'),
      images: [img('Dyson V8 Absolute', '#DCFCE7')]
    },
    {
      id: 70,
      title: 'Mi Robot Vacuum-Mop 2 Pro',
      description: 'LiDAR navigation, 3000Pa suction, smart mapping, 2-in-1 sweeping and mopping.',
      price: 25999,
      discountPercentage: 15,
      rating: 4.3,
      stock: 50,
      brand: 'Xiaomi',
      category: 'home-appliances',
      thumbnail: img('Mi Vacuum-Mop 2 Pro', '#DCFCE7'),
      images: [img('Mi Vacuum-Mop 2 Pro', '#DCFCE7')]
    },
    {
      id: 71,
      title: 'Havells 25L Storage Water Heater Monza EC',
      description: 'Feroglas technology, Incoloy glass-coated heating element, adjustable thermostat.',
      price: 11490,
      discountPercentage: 23,
      rating: 4.2,
      stock: 65,
      brand: 'Havells',
      category: 'home-appliances',
      thumbnail: img('Havells Monza EC 25L', '#DCFCE7'),
      images: [img('Havells Monza EC 25L', '#DCFCE7')]
    },
    {
      id: 72,
      title: 'Bajaj New Shakti Neo 25L Water Heater',
      description: 'Titanium glass lined tank, swirl flow technology, multiple safety systems.',
      price: 8990,
      discountPercentage: 25,
      rating: 4.1,
      stock: 80,
      brand: 'Bajaj',
      category: 'home-appliances',
      thumbnail: img('Bajaj New Shakti Neo 25L', '#DCFCE7'),
      images: [img('Bajaj New Shakti Neo 25L', '#DCFCE7')]
    },
    {
      id: 73,
      title: 'Crompton Ozone 75-Litre Desert Air Cooler',
      description: 'High density honeycomb pads, auto-fill, inverter compatible, 4200 m³/hr airflow.',
      price: 12990,
      discountPercentage: 20,
      rating: 4.2,
      stock: 70,
      brand: 'Crompton',
      category: 'home-appliances',
      thumbnail: img('Crompton Ozone 75L', '#DCFCE7'),
      images: [img('Crompton Ozone 75L', '#DCFCE7')]
    },
    {
      id: 74,
      title: 'Symphony Diet 12T Personal Air Cooler 12L',
      description: 'Compact cooler for small rooms with i-Pure technology and honeycomb pad.',
      price: 7499,
      discountPercentage: 22,
      rating: 4.0,
      stock: 110,
      brand: 'Symphony',
      category: 'home-appliances',
      thumbnail: img('Symphony Diet 12T', '#DCFCE7'),
      images: [img('Symphony Diet 12T', '#DCFCE7')]
    },
    {
      id: 75,
      title: 'Usha Striker Galaxy 1200mm Ceiling Fan',
      description: 'High lift angle blades for wider air spread, glossy powder coated paint.',
      price: 3499,
      discountPercentage: 15,
      rating: 4.2,
      stock: 150,
      brand: 'Usha',
      category: 'home-appliances',
      thumbnail: img('Usha Striker Galaxy Fan', '#DCFCE7'),
      images: [img('Usha Striker Galaxy Fan', '#DCFCE7')]
    },
    {
      id: 76,
      title: 'Orient Electric AeroStorm 1200mm Ceiling Fan',
      description: 'High air delivery aerodynamic blades, powerful motor, elegant design.',
      price: 5999,
      discountPercentage: 18,
      rating: 4.3,
      stock: 120,
      brand: 'Orient Electric',
      category: 'home-appliances',
      thumbnail: img('Orient AeroStorm Fan', '#DCFCE7'),
      images: [img('Orient AeroStorm Fan', '#DCFCE7')]
    },
    {
      id: 77,
      title: 'Godrej 1.5 Ton 3 Star Inverter Split AC',
      description: 'Copper condenser, anti-dust filter, turbo mode, silent operation.',
      price: 38990,
      discountPercentage: 14,
      rating: 4.2,
      stock: 36,
      brand: 'Godrej',
      category: 'home-appliances',
      thumbnail: img('Godrej 1.5T Inverter AC', '#DCFCE7'),
      images: [img('Godrej 1.5T Inverter AC', '#DCFCE7')]
    },
    {
      id: 78,
      title: 'Lloyd 1.0 Ton 3 Star Split AC',
      description: 'Rapid cooling, Clean Filter indication, anti-viral dust filter, copper tubes.',
      price: 30990,
      discountPercentage: 19,
      rating: 4.1,
      stock: 42,
      brand: 'Lloyd',
      category: 'home-appliances',
      thumbnail: img('Lloyd 1.0T 3 Star AC', '#DCFCE7'),
      images: [img('Lloyd 1.0T 3 Star AC', '#DCFCE7')]
    },
    {
      id: 79,
      title: 'Panasonic 1.5 Ton 5 Star Wi‑Fi Inverter AC',
      description: 'AI-enabled 7-in-1 convertible modes, copper condenser, PM 2.5 filter.',
      price: 49990,
      discountPercentage: 12,
      rating: 4.5,
      stock: 28,
      brand: 'Panasonic',
      category: 'home-appliances',
      thumbnail: img('Panasonic Wi‑Fi Inverter AC', '#DCFCE7'),
      images: [img('Panasonic Wi‑Fi Inverter AC', '#DCFCE7')]
    },
    {
      id: 80,
      title: 'Voltas Beko 8 Place Table Top Dishwasher',
      description: '8 place setting, 6 wash programs, compact counter-top dishwasher.',
      price: 23990,
      discountPercentage: 20,
      rating: 4.2,
      stock: 50,
      brand: 'Voltas Beko',
      category: 'home-appliances',
      thumbnail: img('Voltas Beko 8 Place', '#DCFCE7'),
      images: [img('Voltas Beko 8 Place', '#DCFCE7')]
    },

    // Additional Fashion (to reach at least 25 products)
    {
      id: 81,
      title: "Levi's 511 Slim Fit Jeans",
      description: 'Mid-rise, stretch denim, classic 5-pocket styling.',
      price: 3299,
      discountPercentage: 20,
      rating: 4.5,
      stock: 120,
      brand: "Levi's",
      category: 'fashion',
      thumbnail: img("Levi's 511 Jeans", '#FCE7F3'),
      images: [img("Levi's 511 Jeans", '#FCE7F3')]
    },
    {
      id: 82,
      title: 'H&M Cotton Regular Fit T-Shirt',
      description: 'Soft jersey cotton tee with crew neck and short sleeves.',
      price: 799,
      discountPercentage: 15,
      rating: 4.2,
      stock: 200,
      brand: 'H&M',
      category: 'fashion',
      thumbnail: img('H&M Regular Tee', '#FCE7F3'),
      images: [img('H&M Regular Tee', '#FCE7F3')]
    },
    {
      id: 83,
      title: 'ZARA Slim Fit Blazer',
      description: 'Notch lapel, two-button fastening, tailored slim silhouette.',
      price: 7990,
      discountPercentage: 18,
      rating: 4.3,
      stock: 60,
      brand: 'ZARA',
      category: 'fashion',
      thumbnail: img('ZARA Slim Blazer', '#FCE7F3'),
      images: [img('ZARA Slim Blazer', '#FCE7F3')]
    },
    {
      id: 84,
      title: 'Van Heusen Men Formal Trousers',
      description: 'Flat-front formal trousers in poly-viscose blend.',
      price: 1999,
      discountPercentage: 25,
      rating: 4.2,
      stock: 140,
      brand: 'Van Heusen',
      category: 'fashion',
      thumbnail: img('Van Heusen Formal Trousers', '#FCE7F3'),
      images: [img('Van Heusen Formal Trousers', '#FCE7F3')]
    },
    {
      id: 85,
      title: 'Louis Philippe Men Formal Shirt',
      description: 'Cotton-rich slim fit shirt for business wear.',
      price: 2499,
      discountPercentage: 20,
      rating: 4.3,
      stock: 110,
      brand: 'Louis Philippe',
      category: 'fashion',
      thumbnail: img('Louis Philippe Formal Shirt', '#FCE7F3'),
      images: [img('Louis Philippe Formal Shirt', '#FCE7F3')]
    },
    {
      id: 86,
      title: 'Peter England Men Casual Shirt',
      description: 'Checked casual shirt with spread collar and full sleeves.',
      price: 1499,
      discountPercentage: 28,
      rating: 4.1,
      stock: 160,
      brand: 'Peter England',
      category: 'fashion',
      thumbnail: img('Peter England Casual Shirt', '#FCE7F3'),
      images: [img('Peter England Casual Shirt', '#FCE7F3')]
    },
    {
      id: 87,
      title: 'U.S. Polo Assn. Printed Polo T-Shirt',
      description: 'Cotton polo with signature logo print and ribbed collar.',
      price: 1799,
      discountPercentage: 22,
      rating: 4.2,
      stock: 140,
      brand: 'U.S. Polo Assn.',
      category: 'fashion',
      thumbnail: img('USPA Printed Polo', '#FCE7F3'),
      images: [img('USPA Printed Polo', '#FCE7F3')]
    },
    {
      id: 88,
      title: 'Roadster Men Denim Jacket',
      description: 'Light-wash denim jacket with button closure and flap pockets.',
      price: 2999,
      discountPercentage: 25,
      rating: 4.3,
      stock: 90,
      brand: 'Roadster',
      category: 'fashion',
      thumbnail: img('Roadster Denim Jacket', '#FCE7F3'),
      images: [img('Roadster Denim Jacket', '#FCE7F3')]
    },
    {
      id: 89,
      title: 'Mufti Men Slim Fit Jeans',
      description: 'Tapered slim jeans in stretch denim for everyday wear.',
      price: 2799,
      discountPercentage: 20,
      rating: 4.2,
      stock: 100,
      brand: 'Mufti',
      category: 'fashion',
      thumbnail: img('Mufti Slim Jeans', '#FCE7F3'),
      images: [img('Mufti Slim Jeans', '#FCE7F3')]
    },
    {
      id: 90,
      title: 'Wrangler Authentics Straight Fit Jeans',
      description: 'Classic straight fit denim with durable stitching.',
      price: 2499,
      discountPercentage: 18,
      rating: 4.2,
      stock: 120,
      brand: 'Wrangler',
      category: 'fashion',
      thumbnail: img('Wrangler Straight Jeans', '#FCE7F3'),
      images: [img('Wrangler Straight Jeans', '#FCE7F3')]
    },
    {
      id: 91,
      title: 'Lee Men Regular Fit Jeans',
      description: 'Regular fit jeans in comfortable cotton-stretch blend.',
      price: 2599,
      discountPercentage: 22,
      rating: 4.1,
      stock: 130,
      brand: 'Lee',
      category: 'fashion',
      thumbnail: img('Lee Regular Jeans', '#FCE7F3'),
      images: [img('Lee Regular Jeans', '#FCE7F3')]
    },
    {
      id: 92,
      title: 'Biba Women Anarkali Kurta',
      description: 'Printed Anarkali kurta in breathable cotton fabric.',
      price: 2499,
      discountPercentage: 25,
      rating: 4.3,
      stock: 150,
      brand: 'Biba',
      category: 'fashion',
      thumbnail: img('Biba Anarkali Kurta', '#FCE7F3'),
      images: [img('Biba Anarkali Kurta', '#FCE7F3')]
    },
    {
      id: 93,
      title: 'W for Woman Straight Kurta',
      description: 'Solid straight kurta with round neck and 3/4 sleeves.',
      price: 1999,
      discountPercentage: 20,
      rating: 4.2,
      stock: 140,
      brand: 'W for Woman',
      category: 'fashion',
      thumbnail: img('W Straight Kurta', '#FCE7F3'),
      images: [img('W Straight Kurta', '#FCE7F3')]
    },
    {
      id: 94,
      title: 'Aurelia Women Churidar Leggings',
      description: 'Stretchable cotton-blend churidar leggings for ethnic wear.',
      price: 799,
      discountPercentage: 18,
      rating: 4.2,
      stock: 220,
      brand: 'Aurelia',
      category: 'fashion',
      thumbnail: img('Aurelia Churidar Leggings', '#FCE7F3'),
      images: [img('Aurelia Churidar Leggings', '#FCE7F3')]
    },
    {
      id: 95,
      title: 'Fabindia Men Cotton Kurta',
      description: 'Handcrafted cotton kurta with side pockets and mandarin collar.',
      price: 2999,
      discountPercentage: 15,
      rating: 4.4,
      stock: 80,
      brand: 'Fabindia',
      category: 'fashion',
      thumbnail: img('Fabindia Men Kurta', '#FCE7F3'),
      images: [img('Fabindia Men Kurta', '#FCE7F3')]
    },
    {
      id: 96,
      title: 'Manyavar Men Sherwani',
      description: 'Traditional sherwani with embroidered detailing for festive occasions.',
      price: 14999,
      discountPercentage: 12,
      rating: 4.6,
      stock: 30,
      brand: 'Manyavar',
      category: 'fashion',
      thumbnail: img('Manyavar Sherwani', '#FCE7F3'),
      images: [img('Manyavar Sherwani', '#FCE7F3')]
    },
    {
      id: 97,
      title: 'Libas Women Kurta Set',
      description: 'Printed kurta with pants and dupatta set for daily wear.',
      price: 2299,
      discountPercentage: 25,
      rating: 4.3,
      stock: 120,
      brand: 'Libas',
      category: 'fashion',
      thumbnail: img('Libas Kurta Set', '#FCE7F3'),
      images: [img('Libas Kurta Set', '#FCE7F3')]
    },
    {
      id: 98,
      title: 'H&M Women Midi Dress',
      description: 'Flared midi dress with V-neck and short sleeves.',
      price: 2499,
      discountPercentage: 20,
      rating: 4.2,
      stock: 140,
      brand: 'H&M',
      category: 'fashion',
      thumbnail: img('H&M Women Midi Dress', '#FCE7F3'),
      images: [img('H&M Women Midi Dress', '#FCE7F3')]
    },
    {
      id: 99,
      title: 'ZARA Satin Slip Dress',
      description: 'Satin slip dress with adjustable straps and side slit.',
      price: 4590,
      discountPercentage: 15,
      rating: 4.4,
      stock: 70,
      brand: 'ZARA',
      category: 'fashion',
      thumbnail: img('ZARA Satin Slip Dress', '#FCE7F3'),
      images: [img('ZARA Satin Slip Dress', '#FCE7F3')]
    },
    {
      id: 100,
      title: 'Puma Smash v2 Sneakers',
      description: 'Low-profile unisex sneakers with suede upper and rubber outsole.',
      price: 3499,
      discountPercentage: 22,
      rating: 4.5,
      stock: 150,
      brand: 'Puma',
      category: 'fashion',
      thumbnail: img('Puma Smash v2', '#FCE7F3'),
      images: [img('Puma Smash v2', '#FCE7F3')]
    },
    {
      id: 101,
      title: 'Adidas Adilette Aqua Slides',
      description: 'Comfortable slip-on slides with quick-dry cushioning.',
      price: 1999,
      discountPercentage: 20,
      rating: 4.3,
      stock: 180,
      brand: 'Adidas',
      category: 'fashion',
      thumbnail: img('Adidas Adilette Aqua', '#FCE7F3'),
      images: [img('Adidas Adilette Aqua', '#FCE7F3')]
    },
    {
      id: 102,
      title: 'Bata Men Formal Oxford Shoes',
      description: 'Classic lace-up oxfords in polished synthetic leather.',
      price: 2499,
      discountPercentage: 25,
      rating: 4.2,
      stock: 130,
      brand: 'Bata',
      category: 'fashion',
      thumbnail: img('Bata Oxford Shoes', '#FCE7F3'),
      images: [img('Bata Oxford Shoes', '#FCE7F3')]
    },
    {
      id: 103,
      title: 'Woodland Men Leather Boots',
      description: 'Rugged leather boots with high-traction outsole for outdoor wear.',
      price: 5999,
      discountPercentage: 18,
      rating: 4.4,
      stock: 90,
      brand: 'Woodland',
      category: 'fashion',
      thumbnail: img('Woodland Leather Boots', '#FCE7F3'),
      images: [img('Woodland Leather Boots', '#FCE7F3')]
    },
    {
      id: 104,
      title: 'Crocs Classic Clogs',
      description: 'Lightweight, water-friendly clogs with ventilation ports and pivoting heel strap.',
      price: 2995,
      discountPercentage: 15,
      rating: 4.5,
      stock: 160,
      brand: 'Crocs',
      category: 'fashion',
      thumbnail: img('Crocs Classic Clogs', '#FCE7F3'),
      images: [img('Crocs Classic Clogs', '#FCE7F3')]
    },
    {
      id: 105,
      title: 'Nike Air Force 1 \'07',
      description: 'Iconic leather upper, cushioned midsole, classic court style.',
      price: 7995,
      discountPercentage: 10,
      rating: 4.6,
      stock: 120,
      brand: 'Nike',
      category: 'shoes',
      thumbnail: img('Nike Air Force 1', '#FDE68A'),
      images: [img('Nike Air Force 1', '#FDE68A')]
    },
    {
      id: 106,
      title: 'Nike Air Zoom Pegasus 40',
      description: 'Daily training running shoes with responsive Zoom Air cushioning.',
      price: 10995,
      discountPercentage: 12,
      rating: 4.7,
      stock: 90,
      brand: 'Nike',
      category: 'shoes',
      thumbnail: img('Nike Pegasus 40', '#FDE68A'),
      images: [img('Nike Pegasus 40', '#FDE68A')]
    },
    {
      id: 107,
      title: 'Adidas Ultraboost 22',
      description: 'Boost midsole, Primeknit upper, premium comfort for long runs.',
      price: 15999,
      discountPercentage: 20,
      rating: 4.6,
      stock: 70,
      brand: 'Adidas',
      category: 'shoes',
      thumbnail: img('Adidas Ultraboost 22', '#FDE68A'),
      images: [img('Adidas Ultraboost 22', '#FDE68A')]
    },
    {
      id: 108,
      title: 'Adidas Stan Smith',
      description: 'Timeless tennis sneaker with minimalist leather upper.',
      price: 8999,
      discountPercentage: 18,
      rating: 4.5,
      stock: 110,
      brand: 'Adidas',
      category: 'shoes',
      thumbnail: img('Adidas Stan Smith', '#FDE68A'),
      images: [img('Adidas Stan Smith', '#FDE68A')]
    },
    {
      id: 109,
      title: 'Puma RS-X Efekt',
      description: 'Chunky silhouette with bold panels and lightweight cushioning.',
      price: 7999,
      discountPercentage: 22,
      rating: 4.3,
      stock: 95,
      brand: 'Puma',
      category: 'shoes',
      thumbnail: img('Puma RS-X Efekt', '#FDE68A'),
      images: [img('Puma RS-X Efekt', '#FDE68A')]
    },
    {
      id: 110,
      title: 'Puma Softride Pro',
      description: 'SoftFoam+ cushioning with breathable mesh upper for comfort.',
      price: 5599,
      discountPercentage: 20,
      rating: 4.2,
      stock: 140,
      brand: 'Puma',
      category: 'shoes',
      thumbnail: img('Puma Softride Pro', '#FDE68A'),
      images: [img('Puma Softride Pro', '#FDE68A')]
    },
    {
      id: 111,
      title: 'Reebok Classic Leather',
      description: 'Heritage style with leather upper and EVA cushioning.',
      price: 6999,
      discountPercentage: 18,
      rating: 4.4,
      stock: 100,
      brand: 'Reebok',
      category: 'shoes',
      thumbnail: img('Reebok Classic Leather', '#FDE68A'),
      images: [img('Reebok Classic Leather', '#FDE68A')]
    },
    {
      id: 112,
      title: 'Reebok Royal Glide',
      description: 'Retro-inspired sneaker with die-cut EVA midsole.',
      price: 4999,
      discountPercentage: 24,
      rating: 4.2,
      stock: 130,
      brand: 'Reebok',
      category: 'shoes',
      thumbnail: img('Reebok Royal Glide', '#FDE68A'),
      images: [img('Reebok Royal Glide', '#FDE68A')]
    },
    {
      id: 113,
      title: 'New Balance 574 Core',
      description: 'Suede and mesh upper with ENCAP midsole for all-day comfort.',
      price: 8999,
      discountPercentage: 15,
      rating: 4.4,
      stock: 85,
      brand: 'New Balance',
      category: 'shoes',
      thumbnail: img('New Balance 574', '#FDE68A'),
      images: [img('New Balance 574', '#FDE68A')]
    },
    {
      id: 114,
      title: 'New Balance 327',
      description: 'Modern take on 70s running with oversized N logo and lug outsole.',
      price: 9999,
      discountPercentage: 17,
      rating: 4.3,
      stock: 80,
      brand: 'New Balance',
      category: 'shoes',
      thumbnail: img('New Balance 327', '#FDE68A'),
      images: [img('New Balance 327', '#FDE68A')]
    },
    {
      id: 115,
      title: 'ASICS Gel-Kayano 30',
      description: 'Stability running shoes with 4D GUIDANCE SYSTEM and FF BLAST PLUS ECO.',
      price: 15999,
      discountPercentage: 12,
      rating: 4.6,
      stock: 60,
      brand: 'ASICS',
      category: 'shoes',
      thumbnail: img('ASICS Gel-Kayano 30', '#FDE68A'),
      images: [img('ASICS Gel-Kayano 30', '#FDE68A')]
    },
    {
      id: 116,
      title: 'ASICS Gel-Nimbus 25',
      description: 'Max-cushioning daily trainer with PureGEL and soft knit upper.',
      price: 14999,
      discountPercentage: 14,
      rating: 4.5,
      stock: 65,
      brand: 'ASICS',
      category: 'shoes',
      thumbnail: img('ASICS Gel-Nimbus 25', '#FDE68A'),
      images: [img('ASICS Gel-Nimbus 25', '#FDE68A')]
    },
    {
      id: 117,
      title: 'Skechers GOwalk 6',
      description: 'Slip-on walking shoes with ULTRA GO cushioning and Air-Cooled Goga Mat.',
      price: 5999,
      discountPercentage: 20,
      rating: 4.3,
      stock: 140,
      brand: 'Skechers',
      category: 'shoes',
      thumbnail: img('Skechers GOwalk 6', '#FDE68A'),
      images: [img('Skechers GOwalk 6', '#FDE68A')]
    },
    {
      id: 118,
      title: "Skechers D'Lites 4.0",
      description: 'Retro chunky sneakers with cushioned comfort insole.',
      price: 6499,
      discountPercentage: 22,
      rating: 4.2,
      stock: 120,
      brand: 'Skechers',
      category: 'shoes',
      thumbnail: img("Skechers D'Lites 4.0", '#FDE68A'),
      images: [img("Skechers D'Lites 4.0", '#FDE68A')]
    },
    {
      id: 119,
      title: 'Converse Chuck Taylor All Star',
      description: 'Classic canvas high-top sneakers with rubber toe cap.',
      price: 3999,
      discountPercentage: 18,
      rating: 4.5,
      stock: 160,
      brand: 'Converse',
      category: 'shoes',
      thumbnail: img('Converse Chuck Taylor', '#FDE68A'),
      images: [img('Converse Chuck Taylor', '#FDE68A')]
    },
    {
      id: 120,
      title: 'Vans Old Skool',
      description: 'Skate-inspired sneakers with suede and canvas uppers and side stripe.',
      price: 5999,
      discountPercentage: 20,
      rating: 4.4,
      stock: 130,
      brand: 'Vans',
      category: 'shoes',
      thumbnail: img('Vans Old Skool', '#FDE68A'),
      images: [img('Vans Old Skool', '#FDE68A')]
    },
    {
      id: 121,
      title: 'Vans Authentic',
      description: 'Low-top skate shoes with durable canvas upper and waffle outsole.',
      price: 4499,
      discountPercentage: 22,
      rating: 4.3,
      stock: 140,
      brand: 'Vans',
      category: 'shoes',
      thumbnail: img('Vans Authentic', '#FDE68A'),
      images: [img('Vans Authentic', '#FDE68A')]
    },
    {
      id: 122,
      title: 'Hush Puppies Men Derby Leather Shoes',
      description: 'Formal derby shoes with cushioned footbed and durable outsole.',
      price: 5999,
      discountPercentage: 18,
      rating: 4.4,
      stock: 80,
      brand: 'Hush Puppies',
      category: 'shoes',
      thumbnail: img('Hush Puppies Derby', '#FDE68A'),
      images: [img('Hush Puppies Derby', '#FDE68A')]
    },
    {
      id: 123,
      title: 'Red Tape Men Running Shoes RTX-01',
      description: 'Lightweight running shoes with breathable mesh and cushioned sole.',
      price: 2999,
      discountPercentage: 25,
      rating: 4.2,
      stock: 150,
      brand: 'Red Tape',
      category: 'shoes',
      thumbnail: img('Red Tape RTX-01', '#FDE68A'),
      images: [img('Red Tape RTX-01', '#FDE68A')]
    },
    {
      id: 124,
      title: 'Woodland Trekking Boots G-40777',
      description: 'Rugged leather trekking boots with high-traction outsole.',
      price: 6499,
      discountPercentage: 15,
      rating: 4.4,
      stock: 70,
      brand: 'Woodland',
      category: 'shoes',
      thumbnail: img('Woodland Trekking Boots', '#FDE68A'),
      images: [img('Woodland Trekking Boots', '#FDE68A')]
    },
    {
      id: 125,
      title: 'Bata Comfit Loafers',
      description: 'Slip-on loafers with cushioned insole for everyday comfort.',
      price: 2499,
      discountPercentage: 20,
      rating: 4.2,
      stock: 160,
      brand: 'Bata',
      category: 'shoes',
      thumbnail: img('Bata Comfit Loafers', '#FDE68A'),
      images: [img('Bata Comfit Loafers', '#FDE68A')]
    },
    {
      id: 126,
      title: 'Crocs LiteRide Clog',
      description: 'Next-generation LiteRide foam for superior cushioning and comfort.',
      price: 4695,
      discountPercentage: 12,
      rating: 4.5,
      stock: 150,
      brand: 'Crocs',
      category: 'shoes',
      thumbnail: img('Crocs LiteRide Clog', '#FDE68A'),
      images: [img('Crocs LiteRide Clog', '#FDE68A')]
    },
    {
      id: 127,
      title: 'Campus Oxyfit Running Shoes',
      description: 'Breathable upper with springy cushioning for comfort runs.',
      price: 1999,
      discountPercentage: 25,
      rating: 4.1,
      stock: 180,
      brand: 'Campus',
      category: 'shoes',
      thumbnail: img('Campus Oxyfit', '#FDE68A'),
      images: [img('Campus Oxyfit', '#FDE68A')]
    },
    {
      id: 128,
      title: 'Sparx SM-482 Canvas Sneakers',
      description: 'Casual canvas sneakers with cushioned footbed and rubber outsole.',
      price: 1799,
      discountPercentage: 28,
      rating: 4.1,
      stock: 190,
      brand: 'Sparx',
      category: 'shoes',
      thumbnail: img('Sparx SM-482', '#FDE68A'),
      images: [img('Sparx SM-482', '#FDE68A')]
    },
    {
      id: 129,
      title: 'Nike Air Max 270',
      description: 'Visible Max Air unit in heel with mesh upper for lifestyle comfort.',
      price: 12995,
      discountPercentage: 15,
      rating: 4.6,
      stock: 85,
      brand: 'Nike',
      category: 'shoes',
      thumbnail: img('Nike Air Max 270', '#FDE68A'),
      images: [img('Nike Air Max 270', '#FDE68A')]
    }
  ];

  // Use only the curated real catalog so every product is hand-defined and unique
  const products = baseProducts;

  global.LocalData = { products, categories };
})(window);
